DROP TABLE public.Kategoria_miejsc_ekspozycji CASCADE;
DROP TABLE public.Miejsce_ekspozycji CASCADE;
DROP TABLE public.Patron CASCADE;
DROP TABLE public.Wystawa CASCADE;
DROP TABLE public.Kustosz CASCADE;
DROP TABLE public.Umowa CASCADE;
DROP TABLE public.Autor CASCADE;
DROP TABLE public.Styl CASCADE;
DROP TABLE public.Dzielo_sztuki CASCADE;
DROP TABLE public.Udzial_w_tworzeniu_dziela CASCADE;

DROP SEQUENCE public.kategoria_miejsc_ekspozycji_id_seq CASCADE;
DROP SEQUENCE public.miejsce_ekspozycji_id_seq CASCADE;
DROP SEQUENCE public.patron_id_seq CASCADE;
DROP SEQUENCE public.wystawa_id_seq CASCADE;
DROP SEQUENCE public.kustosz_id_seq CASCADE;
DROP SEQUENCE public.autor_id_seq CASCADE;
DROP SEQUENCE public.styl_id_seq CASCADE;
DROP SEQUENCE public.dzielo_sztuki_id_seq CASCADE;
